# Generated by Django 2.2.4 on 2020-01-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Release year')),
                ('rated', models.CharField(max_length=3, null=True, verbose_name='Rated')),
                ('released', models.DateTimeField(verbose_name='Release date')),
                ('runtime', models.CharField(max_length=255, verbose_name='Runtime')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('writer', models.TextField(verbose_name='Writer')),
                ('actors', models.TextField(verbose_name='Actors')),
                ('plot', models.TextField(verbose_name='Plot')),
                ('language', models.TextField(verbose_name='Language')),
                ('country', models.TextField(verbose_name='Country')),
                ('awards', models.TextField(verbose_name='Awards')),
                ('poster', models.CharField(max_length=255, verbose_name='Poster URL')),
                ('imdbid', models.CharField(max_length=255, verbose_name='imDB ID')),
                ('m_type', models.CharField(max_length=255, verbose_name='Type')),
                ('production', models.CharField(max_length=255, verbose_name='Production')),
            ],
            options={
                'verbose_name': 'Movie',
                'ordering': ['title', 'year', 'released'],
            },
        ),
        migrations.CreateModel(
            name='ViewedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(verbose_name='Viewing date')),
                ('note', models.IntegerField(blank=True, null=True, verbose_name='Personal note')),
                ('new', models.BooleanField(verbose_name='Never seen before')),
                ('theater', models.BooleanField(verbose_name='I saw it at theater!')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Viewed movie',
                'ordering': ['note'],
            },
        ),
    ]
