# Generated by Django 2.2.4 on 2020-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True, null=True, verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.TextField(blank=True, null=True, verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='imDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.TextField(blank=True, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, null=True, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Rated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Runtime'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.TextField(blank=True, null=True, verbose_name='Writer'),
        ),
    ]
