# Generated by Django 2.2.4 on 2020-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_watchedmovie_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
