# Generated by Django 2.2.4 on 2020-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200119_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Release year'),
        ),
    ]
