# Generated by Django 2.2.4 on 2020-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200119_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
    ]
