# Generated by Django 2.2.4 on 2020-01-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_watchedmovie_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'ordering': ['view_date', 'note'], 'verbose_name': 'Watched movie'},
        ),
    ]
