# Generated by Django 2.2.4 on 2020-01-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_watchedmovie_viewer'),
        ('moviedirectory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, to='main.WatchedMovie', verbose_name='Watched movies'),
        ),
    ]
