# Generated by Django 2.2.4 on 2020-01-20 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedirectory', '0002_user_watched_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='_user_followed_+', to=settings.AUTH_USER_MODEL, verbose_name='Followed persons'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_followers_+', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
